name: generate-readme

on:
  schedule:
    - cron: "*/5 * * * *"

  workflow_dispatch:

  push:
    branches:
      - master

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - name: Get repository code
        uses: actions/checkout@v3
      - name: Install dependencies
        run: npm ci
      - name: node run index.js
        run: node index.js
      - name: Makefile git add commit push github
        run: |
          ${{ secrets.GH_USER_MAIL }}}
          ${{ secrets.GH_USER_NAME }}}
          git add .
          git commit -m "."
          git push
