name: README build

on:
  push:
    branches:
      - master
  schedule:
    - cron: "*/6 * * * *"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout current repository to Master branch
        uses: actions/checkout@v2
      - name: Setup NodeJs 19.3.0
        uses: actions/setup-node@v2
        with:
          node-version: "19.3.0"
      - name: Cache dependencies and build outputs to improve workflow execution time.
        uses: actions/cache@v2
        with:
          path: node_modules
          key: ${{ runner.os }}-js-${{ hashFiles('package-lock.json') }}
      - name: Install dependencies
        run: npm install
      - name: Generate README file
        run: node index.js
      - name: Generate dark.svg file
        run: node index.js dark
      - name: Commit and Push new README.md and dark.svg
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "Update README.md and dark.svg"
          commit_options: "--signoff"
          commit_user_name: ${{ github.actor }}
          commit_user_email: ${{ github.actor }}@users.noreply.github.com
          commit_author: ${{ github.actor }} <${{ github.actor }}@users.noreply.github.com>
          file_pattern: README.md dark.svg
