name: generate README.md

on:
  schedule:
    - cron: "*/2 * * * *"
  
  workflow_dispatch:

  push:
    branches:
      - master

jobs:
  generate:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout current repository to Master branch
        uses: actions/checkout@v3
      - name: Setup NodeJs 12
        uses: actions/setup-node@v3
        with:
          node-version: "12"
      - name: Install dependencies
        run: npm ci
      - name: node index.js
        run: node index.js
      - name: Makefile git add commit push github
        run: |
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git config --global user.name "github-actions[bot]"
          git add .
          git commit -m "commit from github actions"
          git push