name: README build

on:
  schedule:
    - cron: "*/6 * * * *"
  
  workflow_dispatch:

  push:
    branches:
      - master

jobs:
  generate:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout current repository to Master branch
        uses: actions/checkout@v2
      - name: Setup NodeJs 19.3.0
        uses: actions/setup-node@v2
        with:
          node-version: "19.3.0"
      - name: Cache dependencies and build outputs to improve workflow execution time.
        uses: actions/cache@v2
        with:
          path: node_modules
          key: ${{ runner.os }}-js-${{ hashFiles('package-lock.json') }}
      - name: Install dependencies
        run: npm install
      - name: Generate dark.svg
        run: node index.js
      - name: Commit and Push new dark.svg
        uses: stefanzweifel/git-auto-commit-action@v4
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          commit_message: "Update dark.svg"
          branch: master
          file_pattern: dark.svg
