name: generate dark.svg and light.svg files using node.js

on:
  schedule:
    - cron: "*/2 * * * *"
  
  workflow_dispatch:

  push:
    branches:
      - master

jobs:
  generate:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout current repository to Master branch
        uses: actions/checkout@v3
      - name: Setup NodeJs 19.4.0
        uses: actions/setup-node@v3
        with:
          node-version: "19.4.0"
      - name: Cache dependencies and build outputs to improve workflow execution time.
        uses: actions/cache@v3
        with:
          path: node_modules
          key: ${{ runner.os }}-js-${{ hashFiles('package-lock.json') }}
      - name: Install dependencies
        run: npm install

      - name: Generate dark.svg and light.svg files
        run: node index.js

      - name: Commit and Push new files
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "Update dark.svg and light.svg files"
          commit_options: "--signoff"
          commit_user_name: ${{ github.actor }}
          commit_user_email: ${{ github.actor }}@users.noreply.github.com
          commit_author: ${{ github.actor }} <${{ github.actor }}@users.noreply.github.com>
          file_pattern: "dark.svg,light.svg"
